### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PepeMty** [backdrop-contrib/unique_field#2]
Hey there...!
Most certainly I'm making something wrong here, but I can't make this module work for me.
Installed it as usual in my local machine (ddev), and configured it to work along two fields:
a taxonomy field, from 1 to 11
and a date field.

Created several nodes repeating both inputs.
No joy.

Changed the taxonomy field with a integer number field, again 1 to 11.
Several nodes later repeating both inputs, no joy.

Changed the date field with another integer number field, which served as a date, and left intact the other integer.
A few nodes later, also repeating both inputs and nothing.

Then gave up with the combination values and checked only the faux date field, created a few nodes with the same integer.
Nothing.

Can somebody please point me in the right direction...?

Thanks

Warm regards from sunny México.

**Comment by VasasA** [comment]
@PepeMty Thank You for the issue!
I created a new release of this module: [1.x-1.0.1](https://backdropcms.org/project/unique_field) Please try this!

(Use release 1.x-1.0.0 of Unique Field only for Backdrop 1.14.4 and earlier versions.)

**Comment by PepeMty** [comment]
Thank you, VasasA.
Such a prompt reply.

Warm regards from sunny México.
José
